### ISSUE TITLE
the GUI fallback button at the lower right corner prints the wrong TLLC (always en)

### ISSUE THREAD

**Issue by jgmbenoit** [IMAGINARY/SURFER#2]
It appears that the GUI fallback button at the lower right corner seems to stick to English, whose the Two Letter  Language Code is `en'. In fact not, but it is hard to guess the correct involved TLLC.

**Comment by porst17** [comment]
I forgot to copy over the new gallery files located in https://github.com/IMAGINARY/SURFER1-installer/tree/master/libs. A couple of month ago, I updated the format of the galleries to additionally include the name of the language the gallery text is written in. This information was just missing in this repository here.
