### ISSUE TITLE
the GUI fallback button at the lower right corner machinery get crazy when only one language is available

### ISSUE THREAD

**Issue by jgmbenoit** [IMAGINARY/SURFER#3]
literally : the GUI tries to read files associated to the NULL language, e.g., tutorial_.pdf .

**Comment by porst17** [comment]
The language switcher was introduced when we had three languages (before, there was only a regular button for switching back and forth between German and English). Our designer created a UI element which consists of three different elements: top, middle, bottom. The middle part is repeated if there are more then three languages. Supporting two languages works out of the box by skipping the middle element. However, there is no UI element for supporting one language only. Maybe I can just disable the language switcher in this case. It's not of any use anyway.
