### ISSUE TITLE
free the font size

### ISSUE THREAD

**Issue by jgmbenoit** [IMAGINARY/SURFER#6]
The font size might be unfixed, namely sizeable.
(On may old 15" box, I can hardly read the content unless the GUI fully occupy the screen.)

**Comment by porst17** [comment]
The programs main purpose is to show it in exhibitions. Therefore, all UI components have a fixed design. If you scale the window, all elements are scaled as well, including the font size. The program looks the same on all platforms. It is not integrated in the look-and-feel of the host and this is intended.

This will not be changed for the JavaFX 1.3.1 based implementation of the UI, but we are aiming for a more flexible approach for the JavaFX 8 based version (mainly support different aspect ratios and DPI values of the screen).
